Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
Ans-yes there is a difference  between the data type of list_  and array_list as list_ is list in python while array_list is an numpy array

In [2]:
import numpy as np

In [7]:
list_=[1,2,3,4,5]
type(list_)


list

In [8]:
array_list = np.array(object = list_)
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.

In [9]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [10]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.


In [11]:
array_list = np.array(object = list_, dtype = int)
type(array_list)

numpy.ndarray

for i in array_list:
    print(type(i))

In [13]:
for i in list_:
    print(type(i))
    

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


yes, there will be doifference in the datatypes of the elements in both the variables

Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [16]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
np.size(num_list)

6

In [17]:
np.size(num_array)

6

In [19]:
num_list.reshape(2,3)

<class 'AttributeError'>: 'list' object has no attribute 'reshape'

In [20]:
num_array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [23]:
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [28]:
arr=np.array([1,1,1,1,1])
arr

array([1, 1, 1, 1, 1])

In [29]:
a=np.diag(arr)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])